name: ESLint

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '15 16 * * 6'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run:
          npx eslint . --config .eslintrc.json --ext .js,.jsx,.ts,.tsx --format
          @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
